travis:
  secure:
    BINSTAR_TOKEN: POcF6JLLpolF6UTUsCw6AFYQUTaFMkrw4Zbn4cex295MQ+lDXttTk0vJ6ivYrMB2BfQTkLYoe1uTnWblLOZJboyHW5PxQGOJks4OiL3iKdoy5cPgyye1UHcg6HiDVLndnPIBJ2Fn+l+5Qb7W2q30xotVTftuzo9Xx9elNGTd9vCtGUhkRfAdE6YJo1eb4qqznSMgvSGbbOuKBQJqLUcszqMmnqdB0XK3qcXpoMB8K2MM7x/W5fBjAbyMP2WSsIK69hbpwp7yXQMjSFBnlx9E5iY7e0h27LW5Q0GC7vcDoOrQl3i9x3beVGIIER/HPFSU8M/JRrHSFnpuoJM3XkWOWx7QXfYY29OXweVaT6kP7EgerkyNx2wa764RgWd2AuLFYbPGO7giFBMlMQB1+k5JUOmbk+MprHRI8atWnhvnXP5pFBwgylUSZjsrSvedH1rN96QT06x/qtM9mKdBLbCWrXM6pgloM4tIF9y86lFyt3pmP099mdhGcy6nBhQgCeSA82zbMEq6/3k03/VIekQm/eJ3jwRQ+vksZeISccmPNmXxJApL7zq+jkluBQLvlF1gQsL5xJnDwVRLw1MyFWxXFrp60YkyqYCWF8Scp9xDSiFD1jB/We9a0MRoBFg21htLf3oYJJxclizElyHGjhiKsJpS6yIeI1Ib1nzqcoKasFY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
